### ISSUE TITLE
Support Linux

### ISSUE THREAD

**Issue by xiamaz** [horosproject/horos#112]
I am happy to have found a new project based on the Osirix, which might try to bring some new life to the project. So I am returning an old problem of other OS support.
Why is this important?
Often medical practitioners cannot choose the OS System they can work on, as these are often provided by the hospital. Being able to use the same software on any platform would be a great reason to switch from Osirix to another image viewer.
There are currently no comparable solutions on either Linux or Windows systems, which are not based around huge proprietary frameworks or are aeons old.
Linux is a very flexible OS, easily runnable in VM, thus enabling OS agnostic usage even in enterprise environments. In comparison Windows VMs often require a lot more system resources for the same usage patterns.
There have been attempts to port Osirix to Linux, which mostly failed because of the large xcode codebase. Since this projects seems to attempt to be more than an Osirix clone, I would like to return the discussion. OSX Programs are very unportable, even Windows apps are easier to run on Linux.

Are there plans for porting the codebase to a more OS-agnostic framework?
Attempts at building the program against eg GNUStep, Cappucino?

**Comment by venkatsrinivas** [comment]
YES WE NEED HOROS EVEN FOR LINUX

**Comment by boskar** [comment]
https://osirix4linux.wikispaces.com/ That's all we've got afaik, anybody's got something more?

**Comment by fvpolpeta** [comment]
Hi guys,

Being succinct, the best way to achieve a viewer with the same power of Horos under Linux is starting a new project that relies on Horos only as a spec of want functions and of which open-source libraries to rely on.

A good software engineer with a Mac and PC-Linux could even rewrite functions considering the ones implemented in Horos. But it's virtually impossible to port Horos to Linux due to the COCOA dependencies, on top of which all XIB (Interface Files) and the event bindings are made. 

I, particularly, would do that way, perhaps the only way. ;)

Best

**Comment by fvpolpeta** [comment]
I suggest you guys to keep this kind of question/discussion in the forum.
