### ISSUE TITLE
RIP Horos ?

### ISSUE THREAD

**Issue by boxerab** [horosproject/horos#190]
No code checkins in 7 months ......

**Comment by howardm** [comment]
Unfortunately, this project is clearly defunct. It's too bad.

**Comment by purview-craig** [comment]
Howard -

Thanks for the concern. The Horos community is actually stronger than ever.  We now have over 60,000 global users in over 180 countries. That said, with the community bulging we could always use additional contributors and resources to continue to scale and grow. As the lead sponsor Purview continues to be an integral contributor and has shouldered the lion's share of financing the project.  

We could have gone the way of Pixmeo and turned our free open source product into an advertisement for a paid version.  Instead we are committed to keeping Horos free and open.  We are in the process of engaging additional resources and are searching for additional part-time or full-time paid developers to work on Horos. If you know of anyone please point them our way.

They can apply here:

http://www.purview.net/job/horos-project-software-developer/ <http://www.purview.net/job/horos-project-software-developer/>   

If you or anyone you know would like to contribute to funding a developer to help the project please consider making a donation here: 

https://www.horosproject.org/donate/ <https://www.horosproject.org/donate/>

Thanks for your continued interest in Horos.

Les Trachtman

**Comment by howardm** [comment]
> We could have gone the way of Pixmeo and turned our free open source product into an advertisement for a paid version.  Instead we are committed to keeping Horos free and open.

HM: I really appreciate the gesture.

I previously donated to the Project. I'll do so again if I see progress on fixing and maintaining the code.

As you're aware, a very large number of unresolved code Issues exist in respect of existent versions, as indicated on this site. No one has been working on them for a very long time. I personally cannot use Horos because of them. One example is the broken Anonymization utility in the latest version. (I and others have created an Issue related to this.)

I wish you the best with respect to recruiting a developer(s) for the Project.


Howard,
expectantly but, unfortunately, not optimistically

**Comment by boxerab** [comment]
So, there seems to be a community of users (what's not to like about a free viewer?) but not a community of developers. Most devs would not freely contribute to a GPL-licensed project promoted by a private company, because they realize that the company is most likely going to try to monetize the project at some point. For Horos, likely a commercial, FDA-approved version.  The restrictive GPL license is intended to prevent another commercial entity from forking and developing a competing project. 

Anyways, hopefully for the users sake, this project becomes active again.
