### ISSUE TITLE
Horos and Grok JPEG 2000

### ISSUE THREAD

**Issue by howardm** [horosproject/horos#240]
Hi,

https://github.com/GrokImageCompression/grok

What happened to the incorporation of this compression codec in Horos ?

Thanks.

Howard

**Comment by fvpolpeta** [comment]
Hi Howard -

Now that Horos is LGPL we will work to have this CODEC integrated to the main Horos distribution. Maintaining two different source code repositories due to, and only due to license restrictions was not being optimal. 

We don’t have ETA defined yet, but you can still download the Horos 2K from our website, but not the latest version.

Stay tuned to our future releases. 

Thanks for supporting Horos.

Fauze

**Comment by howardm** [comment]
Great!  Will it perhaps be in version 3.0 when a binary is made available ?

Howard

**Comment by fvpolpeta** [comment]
Yes. We are already working on this. The official/final release is planned to have it.

Thanks for using Horos.

Fauze

**Comment by fvpolpeta** [comment]
Hi -

There is a nightly build that embeds the Grok code. I would like to have volunteers to test it. 

Since it's a new version, with new APIs, I do recommend creating and using a test account in macOS to where you can copy or start a new database. Nothing changed on how your files are handled by Horos (except by the the iCloud Drive detector function), but it's a good practice using a different user account for testing.

https://www.horosproject.org/wp-content/uploads/nightly/Horos3.0.0Nightly20180207.app.zip

Let me know your results.

Thanks

Fauze

**Comment by howardm** [comment]
Works fine. The images load quickly!

Thanks.
