### ISSUE TITLE
Horos and the Horos Community Forum

### ISSUE THREAD

**Issue by howardm** [horosproject/horos#264]
First, I apologize for this posting because it's not a technical issue related to Horos. Of course, delete this Issue after viewing this. 

In viewing of your upcoming "big" announcement on Valentine's day, it would be nice if the Forum could be cleaned up and all the pornography removed. I have previously communicated this, without durable effect.

It would be unfortunate if all your hard work were adversely affected in any way by this.

Sincerely,

Howard

**Comment by horosproject** [comment]
Hi Howard -

Thanks for your message. 

Unfortunately, this forum will be shutdown soon due to some limitations on the anti-spam functions, which are showing not capable of filtering the content as expected. Doing this filtering manually is practically impossible.

You can always post questions in our community at the link below: 

https://groups.google.com/forum/#!forum/horos-project

Or, if you have a specific issue that requires custom technical assistance, you can make a request with our support team for a 15 minute consult. That link is also below.

https://www.horosproject.org/horos-technical-support

Thanks again for using Horos. Stay abreast of exciting future developments by checking back with the Horosproject.org site regularly.

**Comment by howardm** [comment]
Good!  It's still up as of today.

With all the pornography, it reflects very (very!)  badly on the Horos Project !

Howard

**Comment by fvpolpeta** [comment]
Shutdown concluded.
