### ISSUE TITLE
Update Weasis

### ISSUE THREAD

**Issue by nroduit** [horosproject/horos#299]
The [certificate](https://groups.google.com/d/msg/dcm4che/7P905j8fMvU/Za7t_7gQAgAJ) of the current version of Weasis (2.5.3) is out of date.

Weasis can be updated to [3.0.0-RC1](https://sourceforge.net/projects/dcm4che/files/Weasis/). This new release contains some major improvements for image processing, see this [post](https://groups.google.com/d/msg/dcm4che/-UhJcYzVvD0/o8NX27D2BAAJ).

The service building the [jnlp](https://github.com/horosproject/horos/blob/horos/Horos/Resources/WebServicesHTML/weasis.jnlp) file must be updated too, see this [template](https://github.com/nroduit/weasis-pacs-connector/blob/master/src/main/webapp/weasis.jnlp) (note: it contains variables starting by $). Let me know if you need help with this part.

Another improvement would be to call directly the viewer (instead of downloading the jnlp) with the [jnlp protocol](https://github.com/nroduit/weasis-pacs-connector#new-way-to-launch-jnlp). Try on[ the demo server](https://nroduit.github.io/en/demo).

**Comment by fvpolpeta** [comment]
@nroduit 

Hey Nicolas -

Thanks for reporting this. Are you able to do it and make a pull request? 

Otherwise, if you provide some guidance I can follow your instructions and generate a build you can validate.

Thanks again 

Fauze

**Comment by nroduit** [comment]
Hi,

I do not have the time right now but I will try next week.

**Comment by fvpolpeta** [comment]
Thanks a lot for this.

Let me know in case you need something.

Best

Fauze

**Comment by aglv** [comment]
@fvpolpeta I'll take care of this.

**Comment by fvpolpeta** [comment]
Thanks buddy. Coordinate with the Nicolas if appropriate.

Cheers

**Comment by nroduit** [comment]
I think the integration is now clean (still some minor improvements). Thanks @aglv 

Requires also the second commit: https://github.com/volz-io/Horos/commit/214d15ab9f941b31f9fb0e0d8cd4149e1e4a7fcd

**Comment by fvpolpeta** [comment]
Awesome! Awaiting for pull request.

Thanks a lot.

Fauze

**Comment by fvpolpeta** [comment]
https://horosproject.org/horos-content/Horos3.0.0RC3_Nightly20180328.dmg

**Comment by aglv** [comment]
Hey, don't miss this: #304 
Customization files will have to be placed at Library/Application Support/Horos/Weasis and no longer inside the WebServicesHTML dir.

Both /Library and ~/Library are considered. All the contents of the bundled weasis version and of these customization dirs are considered, both for the WebPortal and for the Burn.

In the WebPortal, when /weasis/example.ext is requested,
* if ~/Library/AS/Horos/Weasis/example.ext is available, that file is served;
* otherwise, if /Library/AS/Horos/Weasis/example.ext is available, that file is served;
* otherwise, if Horos.app/Contents/Resources/weasis/example.ext is available, that file is served.

When burning,
* First, all the contents of Horos.app/Contents/Resources/weasis are copied to BurnRoot/weasis
* then, all the contents of /Library/AS/Horos/Weasis are merged into BurnRoot/weasis
* then, all the contents of ~/Library/AS/Horos/Weasis are merged into BurnRoot/weasis

By _merged_, I mean that
* if a file already exists, it is replaced
* if a directory already exists, its subpaths are merged

This means that if a requested file is available in all three locations, the one in ~/Library is served/burned.

This feature is NOT DESCRIBED ANYWHERE in the app, not even a little checkbox/button in the WebPortal preferences.

**Comment by aglv** [comment]
#313 further addresses this
