### ISSUE TITLE
Display contents of usage report to the user.

### ISSUE THREAD

**Issue by eborisch** [horosproject/horos#325]
I can understand the desire to monitor what functions / tools are being used most within Horos, but it would be helpful to show the user the contents of the proposed usage report to be sent -- the first time at a minimum, and every time if the user prefers.

**Comment by nachepri** [comment]
And why do you use a private and closed framework to collect these personal data (homephone.framework) ? What are you trying to hide? Why is this framework not open-source?

**Comment by fvpolpeta** [comment]
Hi -

The only reason we made homephone closed source is because we don't want to keep fully open the way the service connects and authenticates to our backend server. There is no suizzling done in homephone too. 

As the project is open source you can verify/comment/remove all the calls to homephone which are in the form:

[[HorosHomePhone sharedHomePhone] callHomeInformingFunctionType:<FUNCTION USED> detail:@"{}"];

We are just collecting stats on what are the most used modules in Horos. This will enable us to focus where we should pay more attention when bugs or enhancement requests are reported. 

Thanks 

Fauze
