### ISSUE TITLE
Help with the Geometric magnification calculation using the Imager Pixel Spacing Tag in Dicom 0018, 1164

### ISSUE THREAD

**Issue by hawkeyedesi** [horosproject/horos#605]
I have an X-ray Angiogram Image (0008, 0060: XA) that I am viewing on Horos. Now, this DCM does not have the usual Image Pixel spacing (0028, 0030). Instead, it has the Imager Pixel Spacing (0018, 1164). 

Now from the Dicom Standards, I understand that the Imager Pixel Spacing is the distance between the centers of two pixels on the detector screen plate. And that to get the body pixel spacing I need to account for the geometric magnification. 

Here is where I am stuck: I am unable to figure out what the calculation for this conversion is and what other DCM tags are used to parse this information? And which line of code is doing this?  

My aim is to replicate it outside of Horos once I export the annotations and an XML file. Any help would be greatly appreciated.

**Comment by jensen0914** [comment]
I would like to close this as it does not actually seem to be an issue with Horos but a request for doing calibration of resolution.

Basically you need an object of known size to measure in the image. Then you can compute mm/pixel. If in Horos, you can then enter the values in the 2D Viewer->Calibrate Resolution. Be careful with non-square pixels (rare, but some images have non-square pixels). There may be easier ways to do this with Horos, I'm not sure. I haven't had to calibrate an XA image since I worked on Agfa's IMPAX many years ago.

**Comment by hawkeyedesi** [comment]
Thanks for your inputs.
