### ISSUE TITLE
JPEG to DICOM plugin not working in Horos 1.1.7

### ISSUE THREAD

**Issue by DrWhat** [horosproject/horos#64]
Horos 1.1.7 running on OS X 10.11.3

After selecting JPEG images in the plugin’s window, and clicking Choose, nothing happens.

The Console output is pretty sparse:

```
2/19/16 9:41:20.085 PM Horos[24298]: Prepare Filter
2/19/16 9:41:27.553 PM Horos[24298]: -[DICOMExport setSourceDicomImage:]: unrecognized selector sent to instance 0x7f98525a8010
2/19/16 9:41:27.553 PM Horos[24298]: -[DICOMExport setSourceDicomImage:]: unrecognized selector sent to instance 0x7f98525a8010
2/19/16 9:41:27.553 PM Horos[24298]: DICOMExport released
```

(I was importing two images.)

**Comment by doctor80** [comment]
Also had same problem.

**Comment by fvpolpeta** [comment]
We are working to rebuild plugins database and get this working asap.

BR

**Comment by fvpolpeta** [comment]
Hi;

We are working to rebuild the plugin database.

Please, download the last nightly build of Horos, unzip and run it.

https://dl.dropboxusercontent.com/u/15111870/PurView/Horos.app.Nightly%2020160426_205020.zip

Then, download the new build of the JPEG2DICOM plugin at:

https://dl.dropboxusercontent.com/u/15111870/PurView/JPEGtoDICOM.horosplugin.zip

Unzip and double click it for install.

Look forward for your feedback about the plugin. Did it work properly for you.

BR

**Comment by DrWhat** [comment]
That works fine. (Did limited testing, though.) Thanks!

**Comment by fvpolpeta** [comment]
Please, try this build and let me know your findings. The release of version 2.0.0 of Horos will happen soon and your feedback is welcome.

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.dmg

Best Regards

Fauze

**Comment by costabs** [comment]
i have the same issue. The dropbox links are dead. Can you create new download links?

**Comment by fvpolpeta** [comment]
Sorry for this, links are dead because the RC3 is going public very soon. Here is the link:

https://dl.dropboxusercontent.com/u/15111870/PurView/Horos2.0.0RC3.dmg

**Comment by costabs** [comment]
Thank you

2016-06-03 14:00 GMT-03:00 Fauze Polpeta notifications@github.com:

**Comment by costabs** [comment]
Same issue with Horos 2.0
here the console output
Maybe the problem is in the plugin
03/06/16 14:31:50,486 Horos[2539]: -[DICOMExport setSourceDicomImage:]: unrecognized selector sent to instance 0x7fbd6c6cf280
03/06/16 14:31:50,486 Horos[2539]: -[DICOMExport setSourceDicomImage:]: unrecognized selector sent to instance 0x7fbd6c6cf280
03/06/16 14:31:50,486 Horos[2539]: DICOMExport released
03/06/16 14:31:51,034 FinderSyncExt[2554]: host connection <NSXPCConnection: 0x7fcf12f1b1d0> connection from pid 2539 invalidated
03/06/16 14:31:51,035 FinderSyncAPIExtension[2553]: host connection <NSXPCConnection: 0x7fed18f27310> connection from pid 2539 invalidated

**Comment by fvpolpeta** [comment]
I will check that for you later. No worries.

**Comment by fvpolpeta** [comment]
Before anything, please, remove and install the plugin again. Pay attention to do not be using OsiriX not validates plugins. I'm telling you that because I have JPEGtoDICOM (1.7) working here

**Comment by costabs** [comment]
Now it works.
Thanks

2016-06-03 14:38 GMT-03:00 Fauze Polpeta notifications@github.com:
